# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjQs1k7vXu37HFYHpXnHnzNT2mN562Yx
"""

# 1. Install streamlit dan pyngrok/localtunnel
!pip install streamlit -q
!npm install -g localtunnel -q

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Load model dan pendukungnya
model = joblib.load('sample_data/model_churn_best.pkl')
scaler = joblib.load('sample_data/scaler_churn.pkl')
features = joblib.load('sample_data/feature_columns.pkl')

st.set_page_config(page_title="Telco Churn Predictor", layout="centered")

st.title("📊 Telco Customer Churn Prediction")
st.markdown("""
Aplikasi ini memprediksi apakah pelanggan akan berhenti berlangganan (**Churn**) atau tidak.
Masukkan data pelanggan di bawah ini:
""")

# Membuat form input
with st.form("prediction_form"):
    st.subheader("Data Pelanggan")
    col1, col2 = st.columns(2)

    with col1:
        tenure = st.number_input("Tenure (Bulan)", min_value=0, max_value=100, value=1)
        monthly_charges = st.number_input("Monthly Charges ($)", min_value=0.0, value=50.0)
        contract = st.selectbox("Contract", ["Month-to-month", "One year", "Two year"])
        online_security = st.selectbox("Online Security", ["No", "Yes", "No internet service"])

    with col2:
        tech_support = st.selectbox("Tech Support", ["No", "Yes", "No internet service"])
        internet_service = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])
        paperless = st.selectbox("Paperless Billing", ["Yes", "No"])
        total_charges = st.number_input("Total Charges ($)", min_value=0.0, value=50.0)

    submit = st.form_submit_button("Prediksi Sekarang")

if submit:
    # Simulasi encoding sederhana untuk input (sesuaikan dengan LabelEncoder di training)
    # Catatan: Untuk real-app, semua kolom harus dimasukkan sesuai urutan 'features'
    # Di sini kita buat array dummy seukuran fitur training
    input_data = np.zeros(len(features))

    # Isi beberapa fitur utama sebagai contoh logika (mapping sederhana)
    input_data[0] = tenure
    input_data[17] = monthly_charges
    input_data[18] = total_charges

    # Scaling
    input_scaled = scaler.transform([input_data])

    # Prediksi
    prediction = model.predict(input_scaled)
    probability = model.predict_proba(input_scaled)[0][1]

    st.divider()
    if prediction[0] == 1:
        st.error(f"⚠️ Pelanggan diprediksi: **CHURN** (Kemungkinan: {probability:.2%})")
    else:
        st.success(f"✅ Pelanggan diprediksi: **STAY** (Kemungkinan Churn: {probability:.2%})")

!pip install streamlit -q
!npm install -g localtunnel -q
!streamlit run app.py & npx localtunnel --port 8501

model = joblib.load('sample_data/model_churn_best.pkl')
scaler = joblib.load('sample_data/scaler_churn.pkl')
features = joblib.load('sample_data/feature_columns.pkl')